# Generated by Django 6.0.2 on 2026-03-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.SlugField(unique=True)),
                ('emoji', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('color_class', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=100)),
                ('nav_label', models.CharField(max_length=50)),
            ],
        ),
    ]
